# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 01:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_suggestion_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='last_name',
        ),
    ]
